# Generated by Django 4.2.1 on 2023-05-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_details',
            new_name='company',
        ),
    ]
